# Generated by Django 4.1.4 on 2022-12-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budgetadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addbud', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Questionslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addque', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Showplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeadd', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=100)),
            ],
        ),
    ]
