# Generated by Django 4.1.4 on 2022-12-12 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_showplace_quefk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetadd',
            name='quefk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lol', to='app.questionslist'),
        ),
        migrations.AlterField(
            model_name='showplace',
            name='budgetfk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='app.budgetadd'),
        ),
        migrations.AlterField(
            model_name='showplace',
            name='quefk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='que', to='app.questionslist'),
        ),
    ]
